name: treks
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_native_splash: ^2.3.8


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/treks.png
    - assets/profile_pic.png
    - assets/sample_image.jpg

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 400
        - asset: fonts/Inter-Regular.ttf
          weight: 200
